# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6fb059b21c29e56fadacaf49421b125482b17ffb2d53f37d99b5633cb21bc26ca1a414513819397c239e5450ce425ef7ef5739f7ac5a2b30fbc51625aeaf332

test:
  secret_key_base: dbfe8880de5715794cc26b706366267d80b3320e7e3d4cfe0877cef5bf6e904b378a337071ddb90424ec824fb8600b67372b83ac4e8f80b6e5d12c8da206244f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
